// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type POST struct {
	Uuid      string
	Message   sql.NullString
	ReadAt    sql.NullTime
	DeletedAt sql.NullTime
}
